### ISSUE TITLE
Adapting to other endpoints/data

### ISSUE THREAD

**Issue by subins2000** [steevjames/MEC-Attendance-Flutter#1]
Does the app have flexibility or modular wise something to adapt the app for other colleges.

* How is the data obtained currently ?
* How can one change the input data endpoint for other colleges ?
  * What's the format/source of input data

**Comment by steevjames** [comment]
The app is specifically designed for Model Engineering College. Data is scraped from college website using Beautiful Soup library for dart.

Since the app doesn't have any special functionality, its a lot easier to make a new one from scratch incase it has to adapted to new data source. However if card design is required, it can be found in lib/Pages/Attendance/Widgets/createList.dart
